- name: install git
  yum:
    name: git
    state: latest

- name: setup system git config
  command: git config --system http.proxy {{ proxy_env.http_proxy }}
  when: proxy_env.http_proxy|default("") != ""
