- name: Add Jenkins repository
  yum_repository:
    name: Jenkins
    description: Jenkins
    baseurl: https://pkg.jenkins.io/redhat-stable
    enabled: true
    gpgcheck: true
    state: present

- name: Add Jenkins key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install latest jenkins
  yum:
    name: jenkins
    state: latest

- name: copy jenkins sysconfig
  template:
    src: templates/jenkins.sysconfig.j2
    dest: /etc/sysconfig/jenkins
    mode: 0600

- name: create dirs
  file:
    path: /var/lib/jenkins/{{ item }}
    state: directory
    owner: jenkins
    group: jenkins
  with_items:
    - init.groovy.d
    - plugins

- name: copy plugin helper script
  copy:
    src: files/install-jenkins-plugin.sh
    dest: /opt/install-jenkins-plugin.sh
    mode: a+x

- name: install plugins
  command: "/opt/install-jenkins-plugin.sh {{ item }}"
  with_items:
    - azure-ad
    - active-directory
    - antisamy-markup-formatter
    - credentials-binding
    - git
    - http_request
    - slack
    - pipeline-githubnotify-step
    - pipeline-build-step
    - pipeline-stage-step
    - pipeline-stage-view
    - pipeline-utility-steps
    - workflow-basic-steps
    - workflow-cps
    - workflow-durable-task-step

- name: fix ownership
  file:
    path: /var/lib/jenkins/plugins
    owner: jenkins
    group: jenkins
    recurse: yes

- name: copy proxy init script
  template:
    src: templates/jenkins-init-scripts/proxy.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/proxy.groovy
    owner: jenkins
    group: jenkins
  when: proxy_env.http_proxy|default("") != ""

- name: copy azure-ad init script
  template:
    src: templates/jenkins-init-scripts/azure-ad.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/azure-ad.groovy
    owner: jenkins
    group: jenkins
  when: azure_ad_tenant is defined and azure_ad_client is defined and azure_ad_secret is defined and azure_ad_group is defined

- name: copy internal-ad init script
  template:
    src: templates/jenkins-init-scripts/internal-ad.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/internal-ad.groovy
    owner: jenkins
    group: jenkins
  when: internal_ad_domain is defined

- name: copy authorization init script
  template:
    src: templates/jenkins-init-scripts/authorization.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/authorization.groovy
    owner: jenkins
    group: jenkins
  when: azure_ad_group is not defined

- name: copy init scripts
  template:
    src: templates/jenkins-init-scripts/{{ item }}.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/{{ item }}.groovy
    owner: jenkins
    group: jenkins
  with_items:
    - configure-csrf
    - configure-jnlp-agent-protocols
    - configure-git
    - configure-markup-formatter
    - disable-remote-cli
    - security-disable-agent-master
    - tool-maven

- name: Add jenkins to docker group
  user:
    name: jenkins
    group: docker
    append: yes

- name: Setup jenkins git config
  template:
    src: templates/gitconfig.j2
    dest: /var/lib/jenkins/.gitconfig
    owner: jenkins
    group: jenkins
    mode: 0644

- name: Enable and start jenkins service
  systemd:
    name: jenkins
    state: restarted
    enabled: yes

- name: wait for jenkins to boot
  wait_for:
    path: /var/lib/jenkins/jenkins.install.UpgradeWizard.state

- name: bypass setup wizard
  copy:
    src: /var/lib/jenkins/jenkins.install.UpgradeWizard.state
    dest: /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
    owner: jenkins
    group: jenkins
    remote_src: yes

- name: restart jenkins service
  systemd:
    name: jenkins
    state: restarted
